version: "3"
services:
  web:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - "redis"
  redis:
    image: "redis"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    depends_on:
      - web
    ports:
      - "3500:8083"
